---
# autologin to spotify and lastfm spotify plugin
- name: "Copy and fill spotify configuration files (login)"
  template:
    src: ".config/spotify/{{item}}.j2"
    dest: "/home/{{user_name}}/.config/spotify/{{item}}"
    owner: "{{user_name}}"
    group: "{{user_name}}"
  with_items:
    - "prefs"
    - "Users/wouaren-user/prefs"