---
- command: pacman -Q {{item}}
  register: presence
  with_items: packages
  ignore_errors: yes

- name: install package if necessary
  command: yaourt -S {{item.item}} --noconfirm
  when: item|failed
  with_items: presence.results
